### ISSUE TITLE
VPC VSI Autoscaling Not working

### ISSUE THREAD

**Issue by movinglightspeed** [IBM/cloud-enterprise-examples#6]
Hello,
I am having trouble with this script:
https://ibm.github.io/cloud-enterprise-examples/deploy-vsi/setup-environment

I start up a VPC instance and install the script.

Starting server defaultServer.
Server defaultServer started with process ID 2572.
root@test1-kdn4j49mdp-20kqw:~# ufw status
Status: inactive

I am able to install and start the defaultServer. I can verify it running

root@test1-kdn4j49mdp-20kqw:~# sudo netstat -ltnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program                                                                name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      4567/system                                                               d-resolv
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      870/sshd                                                                  
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      2347/sshd:                                                                root@pts
tcp        0      0 127.0.0.1:8125          0.0.0.0:*               LISTEN      12569/stats                                                               ite
tcp6       0      0 127.0.0.1:54611         :::*                    LISTEN      2572/java    <------                                                              
tcp6       0      0 :::22                   :::*                    LISTEN      870/sshd                                                                  
tcp6       0      0 127.0.0.1:9080          :::*                    LISTEN      2572/java   <------                                                               
tcp6       0      0 ::1:6010                :::*                    LISTEN      2347/sshd:                                                                root@pts
tcp6       0      0 127.0.0.1:9443          :::*                    LISTEN      2572/java <------                                                                

However pulling up the script
http://52.116.136.228:9080/autoscale-webapp/HelloWorldServlet
http://52.116.136.228:9080/autoscale-webapp/LoadCPUSquareRoot?count=1

I get error
This site can’t be reached52.116.136.228 refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

This is a blank, brand new ubuntu VPC instance spin up. ufw is disabled, security groups 
![2020-06-02 14_40_17](https://user-images.githubusercontent.com/3288704/83562343-03678680-a4df-11ea-9877-f05c489de0c5.jpg)
have the ports whitelisted.

I am not sure what's wrong, could you advise?

]# nmap 52.116.136.228 -p9080

Starting Nmap 6.40 ( http://nmap.org ) at 2020-06-02 14:42 CDT
Nmap scan report for 52.116.136.228
Host is up (0.00059s latency).
PORT     STATE  SERVICE
9080/tcp closed glrpc

Nmap done: 1 IP address (1 host up) scanned in 0.83 seconds

I don't see a block when I scan the port.

**Comment by balajikadambi** [comment]
@movinglightspeed I am also seeing the issue. Have contacted the product team. Will update you as soon as I get a response.

**Comment by balajikadambi** [comment]
@movinglightspeed We found the issue. The Liberty container has to allow access for a remote client. You could modify the httpEndPoint element in "server.xml" file under /wlp/usr/servers/defaultServer as shown below, and then restart the server.
```
 <!-- To access this server from a remote client add a host attribute to the following element, e.g. host="*" -->
    <httpEndpoint id="defaultHttpEndpoint" host="*"
                  httpPort="9080"
                  httpsPort="9443" />
```
I will be modifying the install script to take care of this. It should be checked in tomorrow.

**Comment by balajikadambi** [comment]
@movinglightspeed I have made changes to the script  to automatically use a server.xml that has the configuration to allow access for remote client. The changes are checked in.
