### ISSUE TITLE
Missing Screenshot

### ISSUE THREAD

**Issue by movinglightspeed** [IBM/cloud-enterprise-examples#7]
The section https://ibm.github.io/cloud-enterprise-examples/monitoring/controlling-access-to-metrics-and-event-data#granting-the-administrative-role mentions

> The screenshot below, shows the Access Group gsi-dbg-test-group’s Edit Policy page and the different role’s assigned for the Platform access and Service access, which can be changed by removing or adding a role. Users that are members of the Access group would also inherit the changes.

However the screenshot is missing, and there is nothing showing access group and associated policies.

**Comment by timroster** [comment]
notified section author - we'll get an update in asap

**Comment by timroster** [comment]
@movinglightspeed - page updated with image
